version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: myUser
    # ports:
    #   - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myUser"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s  

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: myUser
      DB_PASSWORD: 123456
      DB_NAME: myUser
      DB_PORT: 5432
    volumes:
      - .:/app  # Aquí montamos el directorio actual al contenedor  
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
