version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: myPagosDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: myUser
      DB_PASSWORD: 123456
      DB_NAME: myPagosDB
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  db_data:
