// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/merchants": {
            "get": {
                "description": "Obtener una lista de todos los comercios en el sistema.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comercios"
                ],
                "summary": "Obtener todos los comercios",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Merchant"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crear un nuevo comercio en el sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comercios"
                ],
                "summary": "Crear un comercio",
                "parameters": [
                    {
                        "description": "Comercio a crear",
                        "name": "merchant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerMerchantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Merchant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/merchants/{id}": {
            "get": {
                "description": "Obtener los detalles de un comercio específico mediante su ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comercios"
                ],
                "summary": "Obtener un comercio por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del Comercio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Merchant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Actualizar los detalles de un comercio existente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comercios"
                ],
                "summary": "Actualizar un comercio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del Comercio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos actualizados del comercio",
                        "name": "merchant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerMerchantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Merchant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profits": {
            "get": {
                "description": "Obtiene las ganancias de todas las transacciones registradas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ganancias"
                ],
                "summary": "Obtener las ganancias totales",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "number"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProfitErrorResponse"
                        }
                    }
                }
            }
        },
        "/profits/merchant/{merchant_id}": {
            "get": {
                "description": "Obtiene las ganancias de un comercio específico mediante su ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ganancias"
                ],
                "summary": "Obtener las ganancias por comercio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del Comercio",
                        "name": "merchant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "number"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProfitErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProfitErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "description": "Obtener una lista de todas las transacciones realizadas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transacciones"
                ],
                "summary": "Obtener todas las transacciones",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Transaction"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.TransactionErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crear una nueva transacción para un comercio y calcular el fee basado en la comisión.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transacciones"
                ],
                "summary": "Crear una transacción",
                "parameters": [
                    {
                        "description": "Transacción a crear",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.TransactionErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions/merchant/{merchant_id}": {
            "get": {
                "description": "Obtener todas las transacciones de un comercio específico.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transacciones"
                ],
                "summary": "Obtener todas las transacciones de un comercio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del Comercio",
                        "name": "merchant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Transaction"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.TransactionErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions/{id}": {
            "get": {
                "description": "Obtener los detalles de una transacción específica por su ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transacciones"
                ],
                "summary": "Obtener una transacción por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la Transacción",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.TransactionErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handlers.ProfitErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handlers.SwaggerMerchantRequest": {
            "type": "object",
            "properties": {
                "commission": {
                    "type": "integer",
                    "example": 15
                },
                "name": {
                    "type": "string",
                    "example": "comercio123"
                }
            }
        },
        "handlers.SwaggerTransactionRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 100.5
                },
                "merchant_id": {
                    "type": "string",
                    "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
                }
            }
        },
        "handlers.TransactionErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.Merchant": {
            "type": "object",
            "properties": {
                "commission": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "transactions": {
                    "description": "agregamos la relacion",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Transaction"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Transaction": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "commission": {
                    "description": "porcentaje aplicado (tomado del comercio)",
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "fee": {
                    "description": "comisión calculada",
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "merchant_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MyPagosApp API",
	Description:      "Esta es la API de MyPagosApp para manejar comercios y transacciones.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
